insert into biomechanics.cities (city_title) values ('Burgastai');
insert into biomechanics.cities (city_title) values ('Kabor');
insert into biomechanics.cities (city_title) values ('Himanka');
insert into biomechanics.cities (city_title) values ('Wangong');
insert into biomechanics.cities (city_title) values ('Zomba');
insert into biomechanics.cities (city_title) values ('Hankasalmi');
insert into biomechanics.cities (city_title) values ('Palmas Bellas');
insert into biomechanics.cities (city_title) values ('Huai Mek');
insert into biomechanics.cities (city_title) values ('Shums’k');
insert into biomechanics.cities (city_title) values ('Vulcan');
insert into biomechanics.cities (city_title) values ('Baracoa');
insert into biomechanics.cities (city_title) values ('Shicheng');
insert into biomechanics.cities (city_title) values ('Ves?lyy');
insert into biomechanics.cities (city_title) values ('Yuelai');
insert into biomechanics.cities (city_title) values ('Shihuiqiao');
insert into biomechanics.cities (city_title) values ('Rogo?nik');
insert into biomechanics.cities (city_title) values ('Mekon');
insert into biomechanics.cities (city_title) values ('Motygino');
insert into biomechanics.cities (city_title) values ('Trzemeszno');
insert into biomechanics.cities (city_title) values ('Morelos');
insert into biomechanics.cities (city_title) values ('Manizales');
insert into biomechanics.cities (city_title) values ('Totolan');
insert into biomechanics.cities (city_title) values ('Jiamaogong');
insert into biomechanics.cities (city_title) values ('Guif?es');
insert into biomechanics.cities (city_title) values ('Khon San');
insert into biomechanics.cities (city_title) values ('Bothaville');
insert into biomechanics.cities (city_title) values ('Rominimbang');
insert into biomechanics.cities (city_title) values ('Huarong Chengguanzhen');
insert into biomechanics.cities (city_title) values ('Mantes-la-Jolie');
insert into biomechanics.cities (city_title) values ('Stari Lec');
insert into biomechanics.cities (city_title) values ('C?rdoba');
insert into biomechanics.cities (city_title) values ('Lumbangan');
insert into biomechanics.cities (city_title) values ('Philadelphia');
insert into biomechanics.cities (city_title) values ('Kertosari');
insert into biomechanics.cities (city_title) values ('Szczaniec');
insert into biomechanics.cities (city_title) values ('Tr? ?n');
insert into biomechanics.cities (city_title) values ('Fukiage-fujimi');
insert into biomechanics.cities (city_title) values ('Verkhniy Avzyan');
insert into biomechanics.cities (city_title) values ('V?eruby');
insert into biomechanics.cities (city_title) values ('Davyd-Haradok');
insert into biomechanics.cities (city_title) values ('Amorim');
insert into biomechanics.cities (city_title) values ('Maao');
insert into biomechanics.cities (city_title) values ('San Buenaventura');
insert into biomechanics.cities (city_title) values ('Cikoneng');
insert into biomechanics.cities (city_title) values ('Alderetes');
insert into biomechanics.cities (city_title) values ('Link?ping');
insert into biomechanics.cities (city_title) values ('Yulin');
insert into biomechanics.cities (city_title) values ('Tuy Ph???c');
insert into biomechanics.cities (city_title) values ('Roanoke');
insert into biomechanics.cities (city_title) values ('Pondokkaha Kelod');